version: '3.9'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3305:3306

  redis:
    image: redis:5.0.5
    restart: always
    environment:
      REDIS_PASSWORD: redis
    ports:
      - 6378:6379
    volumes:
      - .redisdata:/data

